# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
servlet:
  session:
    timeout: 10

    #设置不参加热部署的文件
spring:
  devtools:
    restart:
      exclude: public/**
      enabled: false